name: "Nightly deploy"

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main", "development" ]
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  nightly:
    name: Deploy nightly
    strategy:
      fail-fast: false
      matrix:
        refs: [main, development]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.refs }}
          submodules: 'recursive'
      - name : Build
        run: |
           ./workflows/autobuild.sh
           ./build_pico_fido.sh
      - name: Update nightly release
        uses: pyTooling/Actions/releaser@main
        with:
          tag: nightly-${{ matrix.refs }}
          rm: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: release/*.*
